Parameters:
    EnvironmentName:
        Type: String
        Default: UdacityProject
    UdacityVPC:
        Type: AWS::EC2::VPC::Id

Resources:
    LBSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allows web traffic to the load balancer.
            VpcId:
              Fn::ImportValue:
                  !Sub '${EnvironmentName}-VPCID'
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 8080
              ToPort: 8080
              CidrIp: 0.0.0.0/0

Outputs:
  VpcId:
    Value: !Ref UdacityVPC
    Export:
      Name: !Sub '${EnvironmentName}-VPCID'