Parameters:
    EnvironmentName:
        Type: String
        Default: UdacityProject
    UdacitySubnet1:
        Type: AWS::EC2::Subnet::Id
    UdacitySubnet2:
        Type: AWS::EC2::Subnet::Id
    UdacityVPC:
        Type: AWS::EC2::VPC::Id
    UdacityVPCZone:
        Type: List<AWS::EC2::Subnet::Id>

Resources:
    LBSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allows web traffic to the load balancer.
            VpcId:
              Fn::Sub: '${EnvironmentName}-VPCID'
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 8080
              ToPort: 8080
              CidrIp: 0.0.0.0/0
    WebServerSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allows HTTP & SSH traffic to the web server.
            VpcId:
              Fn::Sub: '${EnvironmentName}-VPCID'
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 8080
              ToPort: 8080
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 0
              ToPort: 65535
              CidrIp: 0.0.0.0/0
    WebAppLaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            ImageId: ami-005bdb005fb00e791
            UserData:
              Fn::Base64: !Sub |
                #!/bin/bash
                apt-get update -y
                apt-get install unzip awscli -y
                apt-get install apache2 -y
                systemctl start apache2.service
                cd /var/www/html
                aws s3 cp s3://udacity-demo-1/udacity.zip .
                unzip -o udacity.zip
            IamInstanceProfile: !Ref ProfileWithRolesForOurApp
            KeyName: that-one
            SecurityGroups:
            - Ref: WebServerSecGroup
            InstanceType: t3.medium
            BlockDeviceMappings:
            - DeviceName: “/dev/sdk”
              Ebs:
                  VolumeSize: ‘10’
    ProfileWithRolesForOurApp:
        Type: AWS::IAM::InstanceProfile
        Properties: 
            Roles:
                - UdacityS3ReadOnlyEC2
    WebAppGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            VPCZoneIdentifier:
              Fn::Sub: '${EnvironmentName}-PRIV-NETS'
            LaunchConfigurationName: !Ref WebAppLaunchConfig
            MinSize: '2'
            MaxSize: '4'
            TargetGroupARNs:
            - Ref: WebAppTargetGroup
    WebAppLB:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Subnets:
            - Fn::Sub: '${EnvironmentName}-PUB1-SN'
            - Fn::Sub: '${EnvironmentName}-PUB2-SN'
            SecurityGroups:
            - Ref: LBSecGroup
    Listener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            DefaultActions:
            - Type: forward
              TargetGroupArn: !Ref WebAppTargetGroup
            LoadBalancerArn: !Ref WebAppLB
            Port: '80'
            Protocol: HTTP
    ALBListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            Actions:
            - Type: forward
              TargetGroupArn: !Ref WebAppTargetGroup
            Conditions:
            - Field: path-pattern
              Values: [/]
            ListenerArn: !Ref Listener
            Priority: 1
    WebAppTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            HealthCheckIntervalSeconds: 10
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 8
            HealthyThresholdCount: 2
            Port: 8080
            Protocol: HTTP
            UnhealthyThresholdCount: 5
            VpcId:
              Fn::Sub: '${EnvironmentName}-VPCID'

Outputs:
  SubnetId1:
    Value: !Ref UdacitySubnet1
    Export:
      Name: !Sub '${EnvironmentName}-PUB1-SN'
  SubnetId2:
    Value: !Ref UdacitySubnet2
    Export:
      Name: !Sub '${EnvironmentName}-PUB2-SN'
  VpcId:
    Value: !Ref UdacityVPC
    Export:
      Name: !Sub '${EnvironmentName}-VPCID'
  VPCZoneIdentifier:
    Value: !Join
      - ','
      - !Ref UdacityVPCZone
    Export:
      Name: !Sub '${EnvironmentName}-PRIV-NETS'